#!/bin/bash
#
# eos-companion-app-disabler: A system service to enable the companion app
# via d-bus if a file is present.
#
# Copyright (C) 2017 Endless Mobile, Inc.
# Authors:
#  Sam Spilsbury <sam@endlessm.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

gdbus call -y -d com.endlessm.CompanionAppServiceAvahiHelper -o /com/endlessm/CompanionAppServiceAvahiHelper -m com.endlessm.CompanionApp.AvahiHelper.ExitDiscoverableMode
