debian/eos-companion-app-os-integration/lib/systemd/system/*
debian/eos-companion-app-os-integration/usr/lib/*/eos-companion-app-avahi-helper
debian/eos-companion-app-os-integration/usr/share/dbus-1/system.d/com.endlessm.CompanionAppServiceAvahiHelper.conf
debian/eos-companion-app-os-integration/usr/share/dbus-1/system-services/com.endlessm.CompanionAppServiceAvahiHelper.service
debian/eos-companion-app-os-integration/usr/lib/tmpfiles.d/*
